### ISSUE TITLE
I am trying to use the SDK in a different project my using the libraries. Inside WSL2 Ubuntu 22-04

### ISSUE THREAD

**Issue by dbansal-chwy** [orbbec/OrbbecSDK_v2#22]
The error:
`Empty depth frame, continuing:
[11/26 17:25:46.034297][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=659.710MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.078639][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=666.067MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.103987][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=672.425MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.146002][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=678.783MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.190263][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=685.141MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.222289][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=691.499MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.249911][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=697.857MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.302728][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=704.215MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.326692][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=710.573MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.368705][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=716.931MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.404545][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=723.289MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.431521][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=729.647MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.481191][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=736.004MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.514332][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=742.362MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.547715][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=748.720MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.585373][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=755.078MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.625847][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=761.436MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.657823][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=767.794MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.699146][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=774.152MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.737692][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=780.510MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.768353][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=786.868MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.807199][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=793.226MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.845613][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=799.584MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.883136][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=805.941MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.913016][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=812.299MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.925575][warning][89963][Pipeline.cpp:268] Wait for frame timeout, you can try to increase the wait time! current timeout=500 [**1 logs in 4487ms, last: 17:25:42.938790**]
[11/26 17:25:46.940443][debug][89966][Pipeline.cpp:246] Frame received on pipeline! type=Color [**83 logs in 3002ms, last: 17:25:46.918694**]
[11/26 17:25:46.962817][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=818.657MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:46.987120][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=825.015MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:47.027014][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=831.373MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:47.069244][debug][89935][FrameBufferManager.cpp:78] New frame buffer allocated=6.358MB, total usage: allocated=837.731MB, max limit=2048.000MB
Got frameset
Empty depth frame, continuing:
[11/26 17:25:47.090569][warning][89933][ObException.hpp:48] Depth engine create and initialize failed,retCode204
terminate called after throwing an instance of 'libobsensor::io_exception'
  what():  Depth engine create and initialize failed,retCode204`

This is where it ends.

**glxgears is working fine.**

NVIDIA-SMI

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.02              Driver Version: 566.03         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX 5000 Ada Gene...    On  |   00000000:01:00.0 Off |                  Off |
| N/A   44C    P3             25W /   75W |       0MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

The color Stream works fine but as soon as I start depth it start to fail. If i run the examples demo they Work fine/
The following is the custom file.
**CMakeLists.txt file:**

```
cmake_minimum_required(VERSION 3.10)
project(Test)

set(OrbbecSDK_DIR "/home/app/OrbbecSDK-2.0.18")
find_package(OrbbecSDK REQUIRED)
find_package(OpenCV REQUIRED)
set(DEPTHENGINE_PATH /home/app/OrbbecSDK-2.0.18/lib/linux_x64/extensions)


add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory
    ${DEPTHENGINE_PATH}
    ${CMAKE_BINARY_DIR}/extensions/depthengine
)

add_executable(${PROJECT_NAME} src/main.cpp src/camera/capture.cpp)

link_directories(${ORB_LIB_PATH})

target_link_libraries(${PROJECT_NAME}
    OrbbecSDK::OrbbecSDK  # Relative path to libOrbbecSDK.so
    ${OpenCV_LIBS}
)
```

**Comment by Sirudoi** [comment]
Thanks for your feedback! Based on your issue and the log information:

> [11/26 17:25:47.090569][warning][89933][ObException.hpp:48] Depth engine create and initialize failed,retCode204 terminate called after throwing an instance of 'libobsensor::io_exception' what():  Depth engine create and initialize failed,retCode204

It seems that you encountered an issue while initializing the DepthEngine when using the Orbbec Femto Bolt on a Linux system. A solution for similar issues can be found in https://github.com/orbbec/OrbbecSDK-K4A-Wrapper#qa, specifically the third point. You might find a solution there. If the issue persists, please provide more details or relevant source code so we can assist you further.

**Comment by dbansal-chwy** [comment]
Hi @Sirudoi, thank you for the response, but I don't face this issue when running the examples of the SDK,  shouldn't it give the same error there as well?

**Comment by dbansal-chwy** [comment]
And for the following link, what all libraries should I copy:
https://github.com/orbbec/OrbbecSDK_v2/blob/main/docs/tutorial/installation_and_development_guide.md in linux

**Comment by Sirudoi** [comment]
> Hi @Sirudoi, thank you for the response, but I don't face this issue when running the examples of the SDK, shouldn't it give the same error there as well?

Before starting the depth stream in your project, have you called any OpenGL-related APIs? The issue might be related to this. The SDK samples does not involve any OpenGL-related operations. 

Regarding your second question, when using the SDK, you need to copy the `orbbecsdk/lib/extensions` folder to the same directory as your executable. Please make sure to maintain the directory structure of the `extensions` folder, as shown below:
> .
├── build
├── extensions
│   ├── depthengine
│   │   ├── libdepthengine.so
│   │   └── libdepthengine.so.2.0
│   ├── filters
│   │   ├── libFilterProcessor.so
│   │   └── libob_priv_filter.so
│   ├── firmwareupdater
│   │   └── libfirmwareupdater.so
│   └── frameprocessor
│       └── libob_frame_processor.so
└── YourExecutable

I also noticed that in your `CMakeLists.txt`, you are copying the extensions folder to `${CMAKE_BINARY_DIR}/extensions/depthengine`, which could cause some issues. It would be better to modify it to `${CMAKE_BINARY_DIR}/extensions`.

**Comment by dbansal-chwy** [comment]
I user glxgears to test the OpenGL, works fine for me. Also, I was trying pyorbbecsdk as well on WSL2-Ubuntu22-04, but I face same issues there as well.

**Comment by Sirudoi** [comment]
> I user glxgears to test the OpenGL, works fine for me. Also, I was trying pyorbbecsdk as well on WSL2-Ubuntu22-04, but I face same issues there as well.

To avoid the OpenGL context interfering with the initialization of the depth engine, you can try the following steps:
```C++
ob::pipeline pipe
std::shared_ptr<ob::Config> config = std::make_shared<ob::Config>();
config->enableVideoStream(OB_STREAM_DEPTH);

GLFWwindow *currentContext = glfwGetCurrentContext(); // store the current context
glfwMakeContextCurrent(NULL);  // make current context to NULL

pipe.start(config); //  will initialize the DepthEngine

glfwMakeContextCurrent(currentContext); // restore the current context
```

**Comment by dbansal-chwy** [comment]
Hi @Sirudoi , I tried your solution, no depth engine create failed error but the code gets stuck at the following:
ob_capture: ./src/posix_thread.c:64: _glfwPlatformGetTls: Assertion `tls->posix.allocated == GLFW_TRUE' failed.

**Comment by Sirudoi** [comment]
Thank you for your patience in trying, I have not encountered this problem myself. It’s possible that this solution caused a timing issue with GLFW initialization. If possible, could you provide the relevant code snippets to help us assist you better? This was an oversight on our part, and we will add a description of this issue in our future documentation.

**Comment by dbansal-chwy** [comment]
HI @Sirudoi,
I can't share much of code but will do my best:
System: WSL2 - Ubuntu22-04 [All updated]

### NVIDIA-SMI:
**Tue Dec  3 08:54:16 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.02              Driver Version: 566.03         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX 5000 Ada Gene...    On  |   00000000:01:00.0 Off |                  Off |
| N/A    0C    P3             25W /   87W |       0MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+**

### glxinfo -B

**name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA RTX 5000 Ada Generation Laptop GPU) (0xffffffff)
    Version: 23.2.1
    Accelerated: yes
    Video memory: 48540MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 4.2
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA RTX 5000 Ada Generation Laptop GPU)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.2 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
OpenGL shading language version string: 4.20
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.2.1-1ubuntu3.1~22.04.2**

Code Snippets:

`    std::cout<<"Setting up pipeline"<<std::endl;
    ob::Context ctx;
    ctx.setLoggerToConsole(OB_LOG_SEVERITY_INFO);
    mDev = ctx.queryDeviceList()->getDevice(0);

    try
    {   
        m_pipeline = std::make_shared<ob::Pipeline>(mDev);
        m_config = std::make_shared<ob::Config>();
        try{
            auto depthProfiles = m_pipeline->getStreamProfileList(OB_SENSOR_DEPTH);
            try
            {
                auto depthProfile = depthProfiles->getVideoStreamProfile(640, 576, OB_FORMAT_Y16, 30);
                m_config->enableStream(depthProfile);
            }
            catch(ob::Error& e)
            {
                std::cout<<"Selected profile was not found switching to default"<<std::endl;
                auto depthProfile = depthProfiles->getVideoStreamProfile(OB_PROFILE_DEFAULT);
                m_config->enableVideoStream(OB_STREAM_DEPTH);
                std::cout<<"Enabled Depth Stream"<<std::endl;

            }

        }
        catch(ob::Error &e){
            std::cerr << "function:" << e.getName() << "\nargs:" << e.getArgs() << "\nmessage:" << e.getMessage() << "\ntype:" << e.getExceptionType() << std::endl;

        }
        
        auto profiles = m_pipeline->getStreamProfileList(OB_SENSOR_COLOR);
        auto colorProfile = profiles->getVideoStreamProfile(1280, 720, OB_FORMAT_RGB, 15);
        std::cout<<"Enabling Streams"<<std::endl;

        m_config->enableStream(colorProfile);

        std::cout<<"Set up pipeline and config; starting pipeline"<<std::endl;
        m_pipeline->start(m_config);
        std::cout<<"Started Pipeline"<<std::endl;

    }
    catch(ob::Error &e){
        std::cerr<< "Error:" <<e.getMessage() << std::endl;
    }
   `
   
  
When I use this link for especially from point 2, I face this error.
When I build from source, and my code inside the repo and re-build it works fine, not sure what is the problem:
https://github.com/orbbec/OrbbecSDK

Also, for the pre-compiled libraries, the libraries in the extenstion/depthengine, I always get the error: "File too short" I have to copy the files from the source build which solves the error. Is it because the pre-compiled is from linux, and I am inside a WSL2 system?

Thank You.

**Comment by Sirudoi** [comment]
Hello, I apologize for the delayed response.

Regarding the issue you mentioned, where you always encounter the "file too short" error when using the pre-compiled libraries, this could be caused by broken symbolic links.
Please make sure that you haven't extracted the Linux pre-compiled libraries on Windows, as this can break the symbolic links for the depth engine. Alternatively, you can try manually fixing this by running the following commands:
```bash
rm libdepthengine.so
ln -s libdepthengine.so.2.0 libdepthengine.so
```

Regarding the depth engine initialization issue: The depth engine creates an OpenGL context during initialization. If you call OpenGL functions before initializing the depth engine, it could cause an error due to multiple OpenGL contexts being created. A common solution to this is to release the OpenGL context before starting the stream:
```C++
auto currentContext = glfwGetCurrentContext();
glfwMakeContextCurrent(NULL);

m_pipeline->start(m_config); // start stream

glfwMakeContextCurrent(currentContext);
```
Could you help confirm whether the issue you encountered:
> ./src/posix_thread.c:64: _glfwPlatformGetTls: Assertion `tls->posix.allocated == GLFW_TRUE' failed.

is related to OrbbecSDK? Please try commenting out all OrbbecSDK-related code and keep only the OpenGL context storing and restoring logic. I've tried a few scenarios and couldn't reproduce the issue. 

We plan to resolve the multiple OpenGL context issue internally in the SDK in future versions, and we hope to improve this kind of experience going forward. Thank you for your support and usage!
